"""your message here

Revision ID: dbfab3d0e467
Revises: 63f07221fcd0
Create Date: 2025-04-29 16:12:24.875439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbfab3d0e467'
down_revision: Union[str, None] = '63f07221fcd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_devices_device_id', table_name='devices')
    op.drop_index('ix_devices_token', table_name='devices')
    op.drop_table('devices')
    op.add_column('users', sa.Column('provider', sa.String(), nullable=True))
    op.add_column('users', sa.Column('provider_id', sa.String(), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'provider_id')
    op.drop_column('users', 'provider')
    op.create_table('devices',
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('device_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mac_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('revoked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='devices_user_id_fkey'),
    sa.PrimaryKeyConstraint('token', name='devices_pkey')
    )
    op.create_index('ix_devices_token', 'devices', ['token'], unique=False)
    op.create_index('ix_devices_device_id', 'devices', ['device_id'], unique=False)
    # ### end Alembic commands ###
